
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
// Reveal
const io=('IntersectionObserver'in window)?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.07}):null;$$('.reveal').forEach(el=>io?io.observe(el):el.classList.add('visible'));
// Mobile menu
const menu=$('#menu'), nav=$('#navlinks');if(menu&&nav){menu.addEventListener('click',()=>nav.classList.toggle('open'));$$('#navlinks a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
// Home loader, first visit only in session
const homeLoader=$('#homeLoader');if(homeLoader){const seen=sessionStorage.getItem('tct_loader_seen');if(seen){homeLoader.remove();document.documentElement.classList.remove('home-loading')}else{sessionStorage.setItem('tct_loader_seen','1');const start=performance.now();const finish=()=>{const wait=Math.max(0,5500-(performance.now()-start));setTimeout(()=>{document.documentElement.classList.remove('home-loading');homeLoader.classList.add('hide');setTimeout(()=>homeLoader.remove(),950)},wait)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',finish,{once:true});else finish();setTimeout(()=>{if($('#homeLoader')){document.documentElement.classList.remove('home-loading');$('#homeLoader').classList.add('hide')}},8000)}}
// Transition between local pages
const trans=$('#pageTransition');function localPageLink(a){try{const u=new URL(a.href,location.href);return u.origin===location.origin && /(?:index|weather|roads|closures|fixit|news|events|report|about)\.html$/.test(u.pathname)}catch(e){return false}}
$$('a[href]').forEach(a=>a.addEventListener('click',e=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||a.target==='_blank'||!localPageLink(a))return;const u=new URL(a.href,location.href);if(u.href===location.href)return;e.preventDefault();if(!trans){location.href=u.href;return}trans.classList.add('show');trans.setAttribute('aria-hidden','false');setTimeout(()=>location.href=u.href,920)}));window.addEventListener('pageshow',()=>{if(trans){trans.classList.remove('show');trans.setAttribute('aria-hidden','true')}});
// road filters
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('.project').forEach(p=>p.classList.toggle('hidden',f!=='all'&&p.dataset.status!==f))}));
// WIBW tabs
$$('[data-wibw]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-wibw]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=$('#wibwFrame');if(f)f.src=btn.dataset.wibw}));
function iconEmoji(t=''){t=t.toLowerCase();if(t.includes('thunder'))return'⛈️';if(t.includes('snow')||t.includes('sleet'))return'🌨️';if(t.includes('rain')||t.includes('shower'))return'🌧️';if(t.includes('fog'))return'🌫️';if(t.includes('partly')||t.includes('mostly cloudy'))return'⛅';if(t.includes('cloud'))return'☁️';if(t.includes('sun')||t.includes('clear'))return'☀️';return'🌤️'}
function groupForecast(periods){const days=[];for(const p of periods){let key=new Date(p.startTime).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});let d=days.find(x=>x.key===key);if(!d){d={key,date:new Date(p.startTime),day:null,night:null};days.push(d)}if(p.isDaytime)d.day=p;else d.night=p}return days.slice(0,7)}
async function loadWeather(){try{const point=await fetch('https://api.weather.gov/points/39.0473,-95.6752',{headers:{Accept:'application/geo+json'}}).then(r=>{if(!r.ok)throw Error('points');return r.json()});const [forecast,stations]=await Promise.all([fetch(point.properties.forecast).then(r=>r.json()),fetch(point.properties.observationStations).then(r=>r.json())]);const station=stations.features?.[0]?.id;let obs=null;if(station){try{obs=await fetch(station+'/observations/latest').then(r=>r.json())}catch(e){}}const periods=forecast.properties.periods||[],cp=periods[0]||{};let temp=cp.temperature,cond=cp.shortForecast||'Forecast available',wind=cp.windSpeed?`${cp.windSpeed} ${cp.windDirection||''}`:'National Weather Service';if(obs?.properties?.temperature?.value!=null){temp=Math.round(obs.properties.temperature.value*9/5+32);cond=obs.properties.textDescription||cond;const mph=obs.properties.windSpeed?.value!=null?Math.round(obs.properties.windSpeed.value*0.621371):null;if(mph!=null)wind=`Wind ${mph} mph`}$$('[data-temp]').forEach(x=>x.textContent=`${temp}°F`);$$('[data-cond]').forEach(x=>x.textContent=cond);$$('[data-icon]').forEach(x=>x.textContent=iconEmoji(cond));const ht=$('#heroTemp');if(ht)ht.textContent=`${temp}°`;const hc=$('#heroCondition');if(hc)hc.textContent=cond;const hw=$('#heroWind');if(hw)hw.textContent=wind;const wg=$('#weekGrid');if(wg){const days=groupForecast(periods);wg.innerHTML=days.map((d,i)=>{const hi=d.day?.temperature??'--',lo=d.night?.temperature??'--',label=d.day?.shortForecast||d.night?.shortForecast||'',nm=i===0?'Today':d.date.toLocaleDateString('en-US',{weekday:'short'});return `<article class="day-card"><div class="day">${nm}</div><div class="wxemoji">${iconEmoji(label)}</div><div class="temps">${hi}° <span>${lo}°</span></div><div class="forecast-label">${label}</div></article>`}).join('')}const ws=$('#weatherStatus');if(ws){try{const alerts=await fetch('https://api.weather.gov/alerts/active?zone=KSZ039').then(r=>r.json());const c=alerts.features?.length||0;if(c){const names=alerts.features.slice(0,2).map(a=>a.properties.event).join(' • ');ws.insertAdjacentHTML('beforeend',`<span class="status-chip alert">${c} active alert${c===1?'':'s'}: ${names}</span>`)}else ws.insertAdjacentHTML('beforeend','<span class="status-chip">No active Shawnee County weather alerts found</span>')}catch(e){}}}catch(e){$$('[data-temp]').forEach(x=>x.textContent='NWS');$$('[data-cond]').forEach(x=>x.textContent='Weather unavailable');const wg=$('#weekGrid');if(wg)wg.innerHTML='<article class="day-card">Weather service temporarily unavailable.</article>'}}
loadWeather();setInterval(loadWeather,15*60*1000);
